export {default as Homepage} from './Home'
export {default as Services} from './Services'
export {default as Products} from './Products'
export {default as About} from './About'
export {default as Contact} from './Contact'